# Event Extractor Configuration
# Copy this file and rename it to config.yaml, then fill in your API keys

# LLM Configuration
llm:
  # Choose your preferred LLM provider: "openai", "anthropic", or "ollama"
  provider: "openai"

  # API Keys (keep these secure!)
  openai_api_key: "your-openai-api-key-here"
  anthropic_api_key: "your-anthropic-api-key-here"

  # Model settings
  openai_model: "gpt-4"
  anthropic_model: "claude-3-sonnet-20240229"
  ollama_model: "llama2"
  ollama_url: "http://localhost:11434"

  # LLM parameters
  temperature: 0.1
  max_tokens: 1000

# Calendar Configuration
calendar:
  # Default calendar name (leave empty to use default calendar)
  default_calendar: ""

  # Time zone (leave empty to use system timezone)
  timezone: ""

  # Default event duration in minutes for events without end time
  default_duration: 60

  # Default reminder time in minutes before event
  default_reminder: 15

# Text Processing
text:
  # Minimum text length to process
  min_length: 10

  # Maximum text length to process
  max_length: 5000

# Logging
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: "INFO"

  # Log file path (leave empty to log to console only)
  file: ""

# Service Settings
service:
  # Show notification after adding events
  show_notifications: true

  # Confirm before adding events to calendar
  confirm_before_adding: true
